site_name: 'example-docs'
site_description: 'Description of the site'
docs_dir: .
site_dir: site

nav:
  - Home: README.md
  - Index: docs/index.md

plugins:
  - techdocs-core
  - search:
      separator: '[\s\-\.]+'
  - same-dir
  - exclude:
      glob:
        - examples/*
        - node_modules/*
        - packages/*
        - plugins/*
        - site/*
      regex:
